#!/usr/bin/env zsh
# -*- mode: zsh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: ft=zsh tw=120 sw=4 sts=4 et foldmarker=[[[,]]]

typeset -gA TermSupport

@term-supports-notifications() {
    builtin emulate -LR zsh ${=${options[xtrace]:#off}:+-o xtrace}
    builtin setopt extended_glob warn_create_global typeset_silent no_short_loops rc_quotes no_auto_pushd

    if [[ ! -v TermSupport[notifications] ]]; then
        if [[ -v commands[termi] ]]; then
            command termi query desktop-notifications &>/dev/null
        else
            autoload -Uz .term-supports-notifications && .term-supports-notifications
        fi

        (( TermSupport[notifications] = !status ))
    fi

    (( TermSupport[notifications] ))
}

@term-supports-notifications "$@"

