#!/usr/bin/env zsh
# -*- mode: zsh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: ft=zsh tw=120 sw=4 sts=4 et foldmarker=[[[,]]]

.term-cursor-pos2() {
    builtin emulate -LR zsh ${=${options[xtrace]:#off}:+-o xtrace}
    builtin setopt extended_glob warn_create_global typeset_silent no_short_loops rc_quotes no_auto_pushd

    local pos

    # Query terminal.
    builtin read -t 1 -rsd 'R' $'pos?\e[6n' <>/dev/tty 2>&0

    reply=( "${(s.;.)pos##$'\e['}" )
}

.term-cursor-pos2 "$@"
