#!/usr/bin/env zsh
# -*- mode: zsh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: ft=zsh tw=120 sw=4 sts=4 et foldmarker=[[[,]]]

if zmodload zsh/terminfo 2>/dev/null && [[ -v terminfo[sitm] && -v terminfo[ritm] ]]; then
    /usr/bin/grotty -i "$@"
else
    /usr/bin/grotty "$@"
fi
