#!/usr/bin/env zsh
# -*- mode: zsh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# vim: ft=zsh tw=120 sw=4 sts=4 et foldmarker=[[[,]]]

builtin emulate -LR zsh ${=${options[xtrace]:#off}:+-o xtrace}
builtin setopt extended_glob warn_create_global typeset_silent no_short_loops rc_quotes no_auto_pushd

local -a match mbegin mend lines

# Get processes, ignoring last line which is the `ps` process itself.
lines=("${(@)${(@f)$(ps -u $USERNAME -o pid,comm)}[1,-2]}")

# Format output.
lines=("${lines[@]//(#b)( #[^[:space:]]##) (*)/${match[1]} -- ${match[2]}}")

builtin print -l "${lines[@]}"
